---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: fedorium
description: This is my personal OS image.

base-image: quay.io/fedora/fedora-bootc
image-version: 44

modules:
  - type: script
    snippets:
      - echo 'tsflags=nodocs' >> /etc/dnf/dnf.conf

  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        # desktop
        - avengemedia/dms
      files:
        # work
        - https://packages.microsoft.com/yumrepos/vscode/config.repo
    install:
      install-weak-deps: false
      packages:
        # base
        - bat
        - chezmoi
        - fastfetch
        - fzf
        - glibc-all-langpacks
        - libnotify
        - mtools
        - neovim
        - parted
        - xdg-user-dirs
        - zoxide
        - zsh

        # hardware
        - brightnessctl
        - iio-sensor-proxy
        - lshw
        - pciutils
        - playerctl
        - upower
        - usbutils

        ## wireless
        - bluez
        - bluez-tools
        - iwlbluetooth-firmware
        - iwlwifi-mvm-firmware
        - NetworkManager-wifi
        - wpa_supplicant

        ## sound
        - alsa-utils
        - pipewire
        - pipewire-alsa
        - pipewire-pulseaudio
        - pipewire-utils
        - wireplumber

        # desktop
        - dms
        - dms-greeter
        - dsearch
        - flatpak
        - kitty
        - niri
        - plymouth-theme-spinfinity
        - waydroid

        # work
        - code
        - distrobox
        - git
        - podman
        - podman-compose
        - qemu-kvm
        - qemu-img

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          # desktop
          - com.vivaldi.Vivaldi

  - type: systemd
    system:
      enabled:
        # desktop
        - greetd.service

  - type: script
    snippets:
      # desktop
      - systemctl --global add-wants niri.service dms.service
      - rm -f /usr/share/applications/nvim.desktop
      - plymouth-set-default-theme spinfinity

  - type: initramfs
  - type: signing
