---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: fedorium
description: This is my personal OS image.

base-image: quay.io/fedora/fedora-bootc
image-version: 44

modules:
  - type: script
    snippets:
      - echo 'tsflags=nodocs' >> /etc/dnf/dnf.conf

  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        # desktop
        - avengemedia/dms
    install:
      install-weak-deps: false
      packages:
        # base
        - zsh
        - fzf
        - bat
        - zoxide
        - chezmoi
        - glibc-all-langpacks
        - xdg-user-dirs

        # wireless
        - wpa_supplicant
        - NetworkManager-wifi
        - bluez
        - bluez-tools

        # sound
        - pipewire
        - pipewire-alsa
        - pipewire-pulseaudio
        - pipewire-utils
        - wireplumber
        - alsa-utils

        # desktop
        - dms
        - dms-greeter
        - kitty
        - niri
        - waydroid
        - plymouth
        - flatpak

        # work
        - distrobox
        - podman
        - qemu-kvm
        - qemu-img

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          # base
          - io.neovim.nvim

          # desktop
          - com.vivaldi.Vivaldi
          - org.telegram.desktop
          - md.obsidian.Obsidian
          - org.onlyoffice.desktopeditors
          - org.keepassxc.KeePassXC
          - eu.betterbird.Betterbird
          - com.usebottles.bottles
          - io.podman_desktop.PodmanDesktop

          # games
          - com.valvesoftware.Steam
          - com.heroicgameslauncher.hgl

          # work
          - com.visualstudio.code

  - type: systemd
    system:
      enabled:
        # desktop
        - greetd.service

  - type: script
    snippets:
      # desktop
      - systemctl --global add-wants niri.service dms.service

  - type: signing
